import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import SideNav, {
  Toggle,
  Nav,
  NavItem,
  NavIcon,
  NavText,
} from "@trendmicro/react-sidenav";

// Be sure to include styles at some point, probably during your bootstraping
import "@trendmicro/react-sidenav/dist/react-sidenav.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        ></script>
      </Head>

      <SideNav
        onSelect={(selected) => {
          // Add your code here
        }}
        style={{
          background: "#FFFFFF",
          boxShadow:
            "-12px -12px 20px rgba(255, 255, 255, 0.2), 10px 10px 24px rgba(166, 180, 200, 0.15)",
          borderRadius: "40px",
        }}
      >
        <SideNav.Toggle style={{ color: "#666" }} />
        <SideNav.Nav defaultSelected="overview">
          <NavItem eventKey="overview">
            <NavIcon>
              <img src="./assets/overview.svg" alt="overview" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>OVERVIEW</NavText>
          </NavItem>
          <NavItem eventKey="business">
            <NavIcon>
              <img src="./assets/business.svg" alt="business" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>BUSINESS</NavText>
          </NavItem>
          <NavItem eventKey="inbox">
            <NavIcon>
              <img src="./assets/inbox.svg" alt="inbox" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>INBOX</NavText>
          </NavItem>
          <NavItem eventKey="collaborators">
            <NavIcon>
              <img src="./assets/collaborators.svg" alt="collaborators" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>COLLABORATORS</NavText>
          </NavItem>
          <NavItem eventKey="performance">
            <NavIcon>
              <img src="./assets/performance.svg" alt="performance" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>PERFORMANCE</NavText>
            <NavItem eventKey="performance/summary">
              <NavText style={{ color: "#666" }}>SUMMARY</NavText>
            </NavItem>
            <NavItem eventKey="performance/credits">
              <NavText style={{ color: "#666" }}>CREDITS</NavText>
            </NavItem>
            <NavItem eventKey="performance/interestedUsers">
              <NavText style={{ color: "#666" }}>INTERESTED USERS</NavText>
            </NavItem>
          </NavItem>
          <NavItem eventKey="billing">
            <NavIcon>
              <img src="./assets/billing.svg" alt="billing" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>BILLING</NavText>
          </NavItem>
          <NavItem eventKey="support">
            <NavIcon>
              <img src="./assets/support.svg" alt="support" />
            </NavIcon>
            <NavText style={{ color: "#666" }}>SUPPORT</NavText>
          </NavItem>
        </SideNav.Nav>
      </SideNav>
    </div>
  );
}
